### ISSUE TITLE
max_containers is not honored 

### ISSUE THREAD

**Issue by amulyas** [cloudfoundry-community/cf-containers-broker#38] opened 2015-12-02 23:06 UTC
It seems MAX Containers attribute is not honored in CF Container broker ..

**Comment by drnic** [comment] 2015-12-10 18:36
What behavior did you see? 

Also, can you past in a sample of your bosh deployment manifest? Perhaps `max_containers` is mis-configured and not being set correctly?

**Comment by amulyas** [comment] 2015-12-11 04:41
Hello @drnic I will double check if you say so .. dont work on it until I confirm .. meanwhile here is manifest 

properties:
  broker:
    component_name: cf-containers-broker-couchbase-subway
    cookie_secret: 49a40924-ee83-46c1-a9a4-c7605c80bf10
    fetch_images: true
    host: cf-containers-broker-couchbase-subway.xxx.io
    max_containers: 50
    name: xx.xx..x..x..
    password: xxxxxx
    port: 443
    protocol: https
    services:
    - bindable: true


and by the way we are running 6 subway brokers in production :+1:

**Comment by vlerenc** [comment] 2016-01-23 11:27
Can't reproduce the issue. When I configure a setting != 0, I correctly see the following error when trying to create more than the allowed number of service instances: ```Service broker error: Service capacity has been reached```. The ticket is open for quite some time now. I will close it, but feel free to reopen it when you can confirm the issue and please add more context information as well (scenario plain/swarm, manifest).

**Closed by vlerenc** 2016-01-23 11:27 UTC
